director_uuid: (( param "Please set the UUID of your BOSH Director" ))

features:
  use_dns_addresses: false

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-6000000
  max_in_flight: 1
  max_errors: 1
variables: []

name: opensearch

releases:
- {name: opensearch, version: latest}
- {name: routing, version: latest}
- {name: bosh-dns-aliases, version: latest}
- {name: bpm, version: latest}
