instance_groups:
- name: opensearch_manager
  vm_type: t3.medium
  instances: 1
  networks:
  - name: services

- name: opensearch_data
  instances: 3
  vm_type: t3.large

- name: opensearch_dashboards
  vm_type: t3.large
  instances: 1
  jobs:
  - name: route_registrar
    consumes:
      nats-tls:
        deployment: cf-development
        from: nats-tls
    properties:
      route_registrar:
        routes:
        - name: opensearch-dashboard
          port: 5601
          registration_interval: 2s
          timeout: 1s
          uris:
          - logs-beta.dev.us-gov-west-1.aws-us-gov.cloud.gov
    release: routing
  - name: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - deployment: cf-development
          domain: bosh
          instance_group: nats
          network: default
          query: '*'
    release: bosh-dns-aliases

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest
