---
jobs:
- name: build-opensearch-release
  plan:
  - in_parallel:
    - get: release-git-repo
      resource: opensearch-release-git-repo
      trigger: true
    - get: pipeline-tasks
    - get: final-builds-dir-tarball
      resource: opensearch-final-builds-dir-tarball
    - get: releases-dir-tarball
      resource: opensearch-releases-dir-tarball
  - task: finalize-release
    file: pipeline-tasks/finalize-bosh-release.yml
    tags: [iaas]
    params:
      PRIVATE_YML_CONTENT: |-
        ---
        blobstore:
          options:
            region: ((aws-region))
            bucket_name: ((cg-s3-blobstore-bucket))
            credentials_source: env_or_profile
            server_side_encryption: AES256
  - in_parallel:
    - put: opensearch-release
      tags: [iaas]
      params:
        file: finalized-release/opensearch-*.tgz
    - put: opensearch-final-builds-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/final-builds-dir-opensearch.tgz
    - put: opensearch-releases-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/releases-dir-opensearch.tgz

- name: deploy-opensearch-development
  serial_groups: [bosh-development]
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: common-secrets
      resource: common-development
      trigger: true
    - get: opensearch-config
      trigger: true
    - get: opensearch-release
      trigger: true
    - get: opensearch-stemcell-jammy
      trigger: true
  - task: opensearch-manifest
    config:
      <<: *manifest-config
      run:
        path: sh
        args:
        - -exc
        - |
          SPRUCE_FILE_BASE_PATH=opensearch-config spruce merge \
            opensearch-config/opensearch-deployment.yml \
            opensearch-config/opensearch-jobs.yml \
            common-secrets/opensearch-development.yml \
            opensearch-config/opensearch-development.yml \
            > opensearch-manifest/manifest.yml
      outputs:
      - name: opensearch-manifest
      params:
        CF_USERNAME: ((cf-username-development))
        CF_PASSWORD: ((cf-password-development))
        CF_SYSTEM_DOMAIN: ((cf-system-domain-development))
  - put: opensearch-development-deployment
    params: &deploy-params
      manifest: opensearch-manifest/manifest.yml
      releases:
      - opensearch-release/*.tgz
      # - opensearch-for-cloudfoundry-release/*.tgz
      - prometheus-release/*.tgz
      stemcells:
      - opensearch-stemcell-jammy/*.tgz
      ops_files:
      - opensearch-config/nats-tls.yml
  on_failure:
    put: slack
    params: &slack-params
      text: |
        :x: FAILED to deploy opensearch on development
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      <<: *slack-params
      text: |
        :white_check_mark: Successfully deployed opensearch on development
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>


resources:
- name: opensearch-release-git-repo
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: https://github.com/cloud-gov/opensearch-boshrelease
    branch: main

- name: opensearch-final-builds-dir-tarball
  type: s3-iam
  source:
    bucket: ((cg-s3-bosh-releases-bucket))
    versioned_file: final-builds-dir-opensearch.tgz
    region_name: ((aws-region))
    server_side_encryption: AES256

- name: opensearch-releases-dir-tarball
  type: s3-iam
  source:
    bucket: ((cg-s3-bosh-releases-bucket))
    versioned_file: releases-dir-opensearch.tgz
    region_name: ((aws-region))
    server_side_encryption: AES256

- name: master-bosh-root-cert
  type: s3-iam
  source:
    bucket: ((opensearch-private-bucket))
    region_name: ((aws-region))
    versioned_file: master-bosh.crt

- name: common-development
  type: s3-iam
  source:
    bucket: ((opensearch-private-bucket))
    versioned_file: opensearch-development.yml
    region_name: ((aws-region))

- name: opensearch-release
  type: s3-iam
  source:
    bucket: ((cg-s3-bosh-releases-bucket))
    regexp: opensearch-([\d\.]*).tgz
    region_name: ((aws-region))
    server_side_encryption: AES256

- name: opensearch-config
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: ((cg-deploy-opensearch-git-url))

- name: opensearch-stemcell-jammy
  source:
    name: bosh-aws-xen-hvm-ubuntu-jammy-go_agent
  type: bosh-io-stemcell

- name: opensearch-development-deployment
  type: bosh-deployment
  source: &bosh-params-development
    target: ((opensearch-development-deployment-bosh-target))
    client: ((opensearch-development-deployment-bosh-client))
    client_secret: ((opensearch-development-deployment-bosh-client-secret))
    ca_cert: ((opensearch-development-ca-cert))
    deployment: opensearch

- name: pipeline-tasks
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: ((pipeline-tasks-git-url))
    branch: ((pipeline-tasks-git-branch))

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: tests-timer
  type: time
  source:
    interval: 30m

- name: check-backup-timer
  type: time
  source:
    interval: 30m

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
